### ISSUE TITLE
Unhandled exception - KeyError: primaryColor

### ISSUE THREAD

**Issue by nellistc** [ping/libby-calibre-plugin#11]
Error occurs with a configured plugin after performing a sync. Details are pulled from libby/overdrive as expected.

calibre, version 6.25.0
ERROR: Unhandled exception: <b>KeyError</b>:'primaryColor'

calibre 6.25  embedded-python: True
macOS-11.7.3-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.6.0', 'Darwin Kernel Version 20.6.0: Fri Dec 16 00:35:00 PST 2022; root:xnu-7195.141.49~1/RELEASE_X86_64')
Python 3.10.1
OSX: ('11.7.3', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: ... OverDrive Libby (0, 1, 7) ...
Traceback (most recent call last):
  File "calibre_plugins.overdrive_libby.dialog.cards", line 292, in <lambda>
    lambda: self.libby_cards_model_reset(widget_row_pos)
  File "calibre_plugins.overdrive_libby.dialog.cards", line 322, in libby_cards_model_reset
    card_widget = CardWidget(card, library, self, self.cards_tab_widget)
  File "calibre_plugins.overdrive_libby.dialog.cards", line 63, in __init__
    library_card_lbl.setPixmap(self.tab.get_card_pixmap(library))
  File "calibre_plugins.overdrive_libby.dialog.base", line 483, in get_card_pixmap
    stop1.attrib["stop-color"] = library["settings"]["primaryColor"]["hex"]
KeyError: 'primaryColor'

**Comment by nellistc** [comment]
Just to add, there are 2 cards on the account. I've now tried changing the colours on both cards - the error remains.

Thanks for your work on this!

**Comment by ping** [comment]
This looks like it's because the library setup on Libby did not specify default colours. If you're okay with sharing your library names, I would like to check if there's anything else that's different with the library setup.

But in anycase, this should be fixed now. You can download and test with this version [overdrive-libby-plugin-4144cee .zip](https://github.com/ping/libby-calibre-plugin/suites/15774005231/artifacts/900303925).

**Comment by ping** [comment]
This fix is now available in the lastest 0.1.8 release.
