### ISSUE TITLE
Error & suggestion

### ISSUE THREAD

**Issue by p1nkyy** [ping/libby-calibre-plugin#4]
OK finally I got to try the plugin on a release day and here's my report:
- When a hold can't be borrowed for a reason, the Error pop-up message kept staying in the background and can't be closed. I need to close the plugin and close the Error pop-up message. This means re-opening the plugin and the plugin takes time to do synchronization every time it's re-opened.
- I encountered an error when I tried to access my hold at first and I don't know what caused it. I would like to send it to you but through private manner cos I believe there's a sensitive info in it. How can I do so, please?
- It would be great if we could pick which tab is opened at default. I'd like mine to open at 'Holds' every time I open the plugin.
- It would be great if we could multiple select the titles available in Holds. The ACSM Input (through a report for me) has been modified to be able to handle a lot of acsms at once.
- It would be great if we could have a checkbox for each title, Select All, and Deselect All button.

Thanks a lot for reading and trying to accommodate these issues.

**Comment by ping** [comment]
>     * When a hold can't be borrowed for a reason, the Error pop-up message kept staying in the background and can't be closed. I need to close the plugin and close the Error pop-up message. This means re-opening the plugin and the plugin takes time to do synchronization every time it's re-opened.

The actual borrowing of a hold takes place in a calibre job and job errors do not create popups. Also, if an error occurs with a plugin, the unhandled error popup is always on top of the plugin window. The error you described is likely due to some other issue and without any details of the error itself, there is no way to troubleshoot.

>     * I encountered an error when I tried to access my hold at first and I don't know what caused it. I would like to send it to you but through private manner cos I believe there's a sensitive info in it. How can I do so, please?

You can send me a message on mobileread like you've done.
There are 2 errors. The first error is a ClientConnectionError. This is usually temporary in nature. You should just try again.

Regarding the 2nd error, Libby is rejecting that borrow, nothing to do with the plugin. Like you said, you may have run out of quota, or you may need to verify your card through the Libby app.

>     * It would be great if we could pick which tab is opened at default. I'd like mine to open at 'Holds' every time I open the plugin.

I may consider implementing this suggestion in the future. But if your intention is to always know when there are available holds to borrow, the next release will indicate in the tab the number of available holds if any.

>     * It would be great if we could multiple select the titles available in Holds. The ACSM Input (through a report for me) has been modified to be able to handle a lot of acsms at once.
> 
>     * It would be great if we could have a checkbox for each title, Select All, and Deselect All button.

The holds listing is very unlikely to support multiple selection.

1. The right-click on a selected hold is used to edit a hold (suspend/delay). This is a one-at-a-time action.
2. The holds table can display available and unavailable holds. When an unavailable hold is selected, the borrow button is disabled. Multiple-selection will complicate things.

**Comment by p1nkyy** [comment]
1. Hello, next time I encountered this issue I will take a screenshot to make it easier to understand.
2. Re: default tab: to me personally, it is not really to find what holds are available but to check what I have booked and where it is. Also to make it quicker to download when the books arrived.
When that error happened yesterday (loan slot is full, books can't be borrowed, triggered an error pop-up message from Calibre), I had to close the plugin, close the error message, then re-open the plugin. Switching tab is another extra step I feel could be eliminated here.
But of course people's preference don't really matter so I understand if this can't be implemented.
And I don't really use the plugin other than organizing my Holds, really. For my Loan, I've gotten used to over the years to go directly to each library's OD site (hence the first request some time ago) but I do realize the plugin is useful if I'd like to re-download my loan. However since Libby has limitation in the library cards saved (and has since caused error to my Libby many many times (confirmed by OD team as well)) so the plugin can't directly mirror what I do have across all the libraries I have. This is not the plugin's fault of course. I usually go to my email and from there I go to each site directly. Sorry I digress.
3. Understood, thank you for responding.

One question, though, every time the plugin is opened, it's synchronizing, but it also has 'Refresh' button in each tab. Why does it need to synchronize upon opening, what is it synchronizing with? And does it have the same effect with 'Refresh' button?

**Comment by ping** [comment]
If you're saying that the error pop-up is appearing under the plugin windows, that may be a Windows-specific behaviour, because I cannot replicate what you described. I will have to borrow a Windows machine to test what it looks like on Windows.

For most errors, a screenshot is usually not quite enough, please include the text details of the error if you wish to report errors in the future.
![SCR-20230726-oicu](https://github.com/ping/libby-calibre-plugin/assets/104607/38dd309c-a1dc-437d-906d-4a3cdaee0dcc)

The plugin must fetch/sync data from Libby every time it launches because that's where your loan/holds data is coming from.

The Refresh button is a manual trigger for this synchronization process. I may have borrowed a new book from the Libby app on my phone while the plugin is running. There is no way to see this new loan unless the plugin fetches new data from Libby. Without the Refresh button, you will always have to close and re-open the plugin.

The Refresh button on any of the tabs is effectively doing the same thing. It's just a matter of convenience. A single refresh will update all the tabs.

**Comment by p1nkyy** [comment]
The error log is the 2nd part of the log that I sent you. I realized after visiting the library directly it was because I ran out of loan slot. The behavior of the window pop-up is the one that I'm talking about. It stayed grey behind the plugin's window and I can't press _Copy to Clipboard, Show Details_, or _OK_ unless I closed the plugin's window first.

**Comment by ping** [comment]
I suggest you give the test version a try.

Download the artifact from https://github.com/ping/libby-calibre-plugin/actions/runs/5670064789 and install it as a plugin zip.

This test version:
-  has a workaround for the error popup appearing below the plugin window
- remembers the last tab you used, so if you only use the Holds tab, it will open that tab by default

**Comment by p1nkyy** [comment]
Thank you, will report back next Tuesday!

**Comment by p1nkyy** [comment]
[libby.txt](https://github.com/ping/libby-calibre-plugin/files/12224909/libby.txt)

Hello, today is 90% smooth. I got some error when borrowing the holds, I don't know why, they seem to bounce back over & over, I only managed to copy 1 error log, the one above.
Thankfully the hold that didn't get borrowed in the first time re-appeared in the Hold list so I can re-download it.
Some books got borrowed but didn't get downloaded. I wonder why. When I went to OD directly and downloaded the epub, it asked confirmation whether I have ADE (as you might know this only happens when you download from the library first time that day) so it means the plugin managed to borrow it but not download it. I learned that maybe I was hammering it too much so I stopped at 10 jobs or so.
Kudos to you for making this beautiful UI for this plugin. I realize now seeing the jobs queue in the bottom of Calibre is very useful. I might ask ACSM Input to implement this as well. Thank you!

**Comment by p1nkyy** [comment]
Hi, I tried **15042cd**, doesn't run as smoothly as prev version if I may say.

[libby 15042cd.txt](https://github.com/ping/libby-calibre-plugin/files/12262092/libby.15042cd.txt)

Got the below error message every single time I open it or switching tabs.

![image](https://github.com/ping/libby-calibre-plugin/assets/7593831/224e2423-50a1-484c-b063-91cdcc017d4c)

Card tab can only display 3 cards, all with 'A' prefix. One doesn't even show proper name and card details and overlapped with the Refresh button.

I love the card tab but what is the use exactly? Besides knowing the hold & loan limits, what else can we do with it?

Thank you in advance!

**Comment by ping** [comment]
You can test with this version [overdrive-libby-plugin-0618e99.zip](https://github.com/ping/libby-calibre-plugin/suites/14830205324/artifacts/844360789) which should fix the error and display issue.

The Cards tab also provides shortcuts to OverDrive/Libby. In the tab, if you right click on the library name, loans limit, holds limit, there will be options to go to OverDrive or Libby. For Libby, the loans/holds list will be automatically filtered by the library selected.

![cards](https://github.com/ping/libby-calibre-plugin/assets/104607/6e875feb-dec7-4960-bbab-eb2f13f6d1b1)

This [test version 0618e99](https://github.com/ping/libby-calibre-plugin/suites/14830205324/artifacts/844360789) also introduces a basic search function to search across libraries. The search is limited to a maximum of 24 linked libraries which should be enough for the vast majority of people. If you have more than 24 linked libraries, you may want to specify which 24 to search in. This can be done in Customize plugin, by specifying the library key codes seen in the Cards tab.

![search](https://github.com/ping/libby-calibre-plugin/assets/104607/25e51a45-85e0-4d39-b810-9e80307ecf28)

**Comment by p1nkyy** [comment]
Wow I'd say you're a genius, you're implementing more & more stuff. Hope you don't feel bothered with all my reports & requests. For now everything looks proper and works the way it's intended to be. Will report back next Tuesday.

**Comment by ping** [comment]
New test version at #6 and also posted on MR.

I'm going to close this issue since there isn't any specific unresolved issue. Please report any problems with the test version at the linked issue.
